### ISSUE TITLE
ENV Key

### ISSUE THREAD

**Issue by luvnft** [beeinger/eth-warsaw#10]
can you provide demos of ENV KEY? 

NEXT_PUBLIC_API_URL=
NEXT_PUBLIC_TRANSACTIONS_PER_TRACK=
NEXT_PUBLIC_SELF_URL=

**Comment by beeinger** [comment]
Oh boy I don't think it works anymore, but here you are:
```env
NEXT_PUBLIC_API_URL=https://voyager.online/api
NEXT_PUBLIC_TRANSACTIONS_PER_TRACK=8
NEXT_PUBLIC_SELF_URL=https://techn.ooo
```
